version: '3.3'
services:
  manager:
    image: rayyanqcri/swarm-scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DOCKER_URL=unix:///var/run/docker.sock
      - TZ=America/New_York
    configs:
      - source: crontab.v1
        target: crontab
    deploy:
      placement:
        constraints:
          - node.role == manager
configs:
  crontab.v1:
    external: true

